### ISSUE TITLE
Fix the dragon

### ISSUE THREAD

**Issue by Unitoch** [sparklingrobots/nano2017#1]
It's broken.

**Comment by sparklingrobots** [comment]
The horns work.

**Comment by Unitoch** [comment]
Excellent, now use that pattern to fix the rest.

**Comment by Unitoch** [comment]
This does it: #2

**Comment by sparklingrobots** [comment]
YOU WITH YOUR STANDARDS

**Comment by sparklingrobots** [comment]
Closed because @Unitoch fixed the dragon I was too lazy to fix.
